# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Tears
tagline:          'Tech rants and tutorials'
description:      'Tech rants and tutorials'
url:              http://tears.io
baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0

gems: [jekyll-paginate, jekyll-gist]
